[package]
name = "wizer"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "wizer"
required-features = ["env_logger", "structopt"]

[dependencies]
anyhow = "1.0.34"
env_logger = { version = "0.8.1", optional = true }
log = "0.4.11"
structopt = { version = "0.3.20", optional = true }
wasm-encoder = "0.1.0"
wasmparser = "0.68.0"
wasmtime = "0.21.0"
wasmtime-wasi = "0.21.0"

[dev-dependencies]
wat = "1.0.28"
env_logger = "0.8.2"

[workspace]
members = [
    "tests/regex-test"
]
